# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/acw9iism5wr6mxaq54h306bbxnl27n63-cmake-3.16.3/bin/cmake

# The command to remove a file.
RM = /nix/store/acw9iism5wr6mxaq54h306bbxnl27n63-cmake-3.16.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tathougies/Projects/clusterd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tathougies/Projects/clusterd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nix/store/acw9iism5wr6mxaq54h306bbxnl27n63-cmake-3.16.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/nix/store/acw9iism5wr6mxaq54h306bbxnl27n63-cmake-3.16.3/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tathougies/Projects/clusterd/CMakeFiles /home/tathougies/Projects/clusterd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tathougies/Projects/clusterd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clusterd-controller

# Build rule for target.
clusterd-controller: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clusterd-controller
.PHONY : clusterd-controller

# fast build rule for target.
clusterd-controller/fast:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/build
.PHONY : clusterd-controller/fast

#=============================================================================
# Target rules for targets named clusterd-service

# Build rule for target.
clusterd-service: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clusterd-service
.PHONY : clusterd-service

# fast build rule for target.
clusterd-service/fast:
	$(MAKE) -f CMakeFiles/clusterd-service.dir/build.make CMakeFiles/clusterd-service.dir/build
.PHONY : clusterd-service/fast

#=============================================================================
# Target rules for targets named clusterd-monitor

# Build rule for target.
clusterd-monitor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clusterd-monitor
.PHONY : clusterd-monitor

# fast build rule for target.
clusterd-monitor/fast:
	$(MAKE) -f CMakeFiles/clusterd-monitor.dir/build.make CMakeFiles/clusterd-monitor.dir/build
.PHONY : clusterd-monitor/fast

#=============================================================================
# Target rules for targets named clusterd-host

# Build rule for target.
clusterd-host: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clusterd-host
.PHONY : clusterd-host

# fast build rule for target.
clusterd-host/fast:
	$(MAKE) -f CMakeFiles/clusterd-host.dir/build.make CMakeFiles/clusterd-host.dir/build
.PHONY : clusterd-host/fast

#=============================================================================
# Target rules for targets named clusterctl

# Build rule for target.
clusterctl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clusterctl
.PHONY : clusterctl

# fast build rule for target.
clusterctl/fast:
	$(MAKE) -f CMakeFiles/clusterctl.dir/build.make CMakeFiles/clusterctl.dir/build
.PHONY : clusterctl/fast

#=============================================================================
# Target rules for targets named clusterd-ns

# Build rule for target.
clusterd-ns: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clusterd-ns
.PHONY : clusterd-ns

# fast build rule for target.
clusterd-ns/fast:
	$(MAKE) -f CMakeFiles/clusterd-ns.dir/build.make CMakeFiles/clusterd-ns.dir/build
.PHONY : clusterd-ns/fast

src/programs/clusterctl.o: src/programs/clusterctl.c.o

.PHONY : src/programs/clusterctl.o

# target to build an object file
src/programs/clusterctl.c.o:
	$(MAKE) -f CMakeFiles/clusterctl.dir/build.make CMakeFiles/clusterctl.dir/src/programs/clusterctl.c.o
.PHONY : src/programs/clusterctl.c.o

src/programs/clusterctl.i: src/programs/clusterctl.c.i

.PHONY : src/programs/clusterctl.i

# target to preprocess a source file
src/programs/clusterctl.c.i:
	$(MAKE) -f CMakeFiles/clusterctl.dir/build.make CMakeFiles/clusterctl.dir/src/programs/clusterctl.c.i
.PHONY : src/programs/clusterctl.c.i

src/programs/clusterctl.s: src/programs/clusterctl.c.s

.PHONY : src/programs/clusterctl.s

# target to generate assembly for a file
src/programs/clusterctl.c.s:
	$(MAKE) -f CMakeFiles/clusterctl.dir/build.make CMakeFiles/clusterctl.dir/src/programs/clusterctl.c.s
.PHONY : src/programs/clusterctl.c.s

src/programs/clusterd-controller.o: src/programs/clusterd-controller.c.o

.PHONY : src/programs/clusterd-controller.o

# target to build an object file
src/programs/clusterd-controller.c.o:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/clusterd-controller.c.o
.PHONY : src/programs/clusterd-controller.c.o

src/programs/clusterd-controller.i: src/programs/clusterd-controller.c.i

.PHONY : src/programs/clusterd-controller.i

# target to preprocess a source file
src/programs/clusterd-controller.c.i:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/clusterd-controller.c.i
.PHONY : src/programs/clusterd-controller.c.i

src/programs/clusterd-controller.s: src/programs/clusterd-controller.c.s

.PHONY : src/programs/clusterd-controller.s

# target to generate assembly for a file
src/programs/clusterd-controller.c.s:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/clusterd-controller.c.s
.PHONY : src/programs/clusterd-controller.c.s

src/programs/clusterd-db.o: src/programs/clusterd-db.c.o

.PHONY : src/programs/clusterd-db.o

# target to build an object file
src/programs/clusterd-db.c.o:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/clusterd-db.c.o
.PHONY : src/programs/clusterd-db.c.o

src/programs/clusterd-db.i: src/programs/clusterd-db.c.i

.PHONY : src/programs/clusterd-db.i

# target to preprocess a source file
src/programs/clusterd-db.c.i:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/clusterd-db.c.i
.PHONY : src/programs/clusterd-db.c.i

src/programs/clusterd-db.s: src/programs/clusterd-db.c.s

.PHONY : src/programs/clusterd-db.s

# target to generate assembly for a file
src/programs/clusterd-db.c.s:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/clusterd-db.c.s
.PHONY : src/programs/clusterd-db.c.s

src/programs/clusterd-host.o: src/programs/clusterd-host.c.o

.PHONY : src/programs/clusterd-host.o

# target to build an object file
src/programs/clusterd-host.c.o:
	$(MAKE) -f CMakeFiles/clusterd-host.dir/build.make CMakeFiles/clusterd-host.dir/src/programs/clusterd-host.c.o
.PHONY : src/programs/clusterd-host.c.o

src/programs/clusterd-host.i: src/programs/clusterd-host.c.i

.PHONY : src/programs/clusterd-host.i

# target to preprocess a source file
src/programs/clusterd-host.c.i:
	$(MAKE) -f CMakeFiles/clusterd-host.dir/build.make CMakeFiles/clusterd-host.dir/src/programs/clusterd-host.c.i
.PHONY : src/programs/clusterd-host.c.i

src/programs/clusterd-host.s: src/programs/clusterd-host.c.s

.PHONY : src/programs/clusterd-host.s

# target to generate assembly for a file
src/programs/clusterd-host.c.s:
	$(MAKE) -f CMakeFiles/clusterd-host.dir/build.make CMakeFiles/clusterd-host.dir/src/programs/clusterd-host.c.s
.PHONY : src/programs/clusterd-host.c.s

src/programs/clusterd-monitor.o: src/programs/clusterd-monitor.c.o

.PHONY : src/programs/clusterd-monitor.o

# target to build an object file
src/programs/clusterd-monitor.c.o:
	$(MAKE) -f CMakeFiles/clusterd-monitor.dir/build.make CMakeFiles/clusterd-monitor.dir/src/programs/clusterd-monitor.c.o
.PHONY : src/programs/clusterd-monitor.c.o

src/programs/clusterd-monitor.i: src/programs/clusterd-monitor.c.i

.PHONY : src/programs/clusterd-monitor.i

# target to preprocess a source file
src/programs/clusterd-monitor.c.i:
	$(MAKE) -f CMakeFiles/clusterd-monitor.dir/build.make CMakeFiles/clusterd-monitor.dir/src/programs/clusterd-monitor.c.i
.PHONY : src/programs/clusterd-monitor.c.i

src/programs/clusterd-monitor.s: src/programs/clusterd-monitor.c.s

.PHONY : src/programs/clusterd-monitor.s

# target to generate assembly for a file
src/programs/clusterd-monitor.c.s:
	$(MAKE) -f CMakeFiles/clusterd-monitor.dir/build.make CMakeFiles/clusterd-monitor.dir/src/programs/clusterd-monitor.c.s
.PHONY : src/programs/clusterd-monitor.c.s

src/programs/clusterd-ns.o: src/programs/clusterd-ns.c.o

.PHONY : src/programs/clusterd-ns.o

# target to build an object file
src/programs/clusterd-ns.c.o:
	$(MAKE) -f CMakeFiles/clusterd-ns.dir/build.make CMakeFiles/clusterd-ns.dir/src/programs/clusterd-ns.c.o
.PHONY : src/programs/clusterd-ns.c.o

src/programs/clusterd-ns.i: src/programs/clusterd-ns.c.i

.PHONY : src/programs/clusterd-ns.i

# target to preprocess a source file
src/programs/clusterd-ns.c.i:
	$(MAKE) -f CMakeFiles/clusterd-ns.dir/build.make CMakeFiles/clusterd-ns.dir/src/programs/clusterd-ns.c.i
.PHONY : src/programs/clusterd-ns.c.i

src/programs/clusterd-ns.s: src/programs/clusterd-ns.c.s

.PHONY : src/programs/clusterd-ns.s

# target to generate assembly for a file
src/programs/clusterd-ns.c.s:
	$(MAKE) -f CMakeFiles/clusterd-ns.dir/build.make CMakeFiles/clusterd-ns.dir/src/programs/clusterd-ns.c.s
.PHONY : src/programs/clusterd-ns.c.s

src/programs/clusterd-service.o: src/programs/clusterd-service.c.o

.PHONY : src/programs/clusterd-service.o

# target to build an object file
src/programs/clusterd-service.c.o:
	$(MAKE) -f CMakeFiles/clusterd-service.dir/build.make CMakeFiles/clusterd-service.dir/src/programs/clusterd-service.c.o
.PHONY : src/programs/clusterd-service.c.o

src/programs/clusterd-service.i: src/programs/clusterd-service.c.i

.PHONY : src/programs/clusterd-service.i

# target to preprocess a source file
src/programs/clusterd-service.c.i:
	$(MAKE) -f CMakeFiles/clusterd-service.dir/build.make CMakeFiles/clusterd-service.dir/src/programs/clusterd-service.c.i
.PHONY : src/programs/clusterd-service.c.i

src/programs/clusterd-service.s: src/programs/clusterd-service.c.s

.PHONY : src/programs/clusterd-service.s

# target to generate assembly for a file
src/programs/clusterd-service.c.s:
	$(MAKE) -f CMakeFiles/clusterd-service.dir/build.make CMakeFiles/clusterd-service.dir/src/programs/clusterd-service.c.s
.PHONY : src/programs/clusterd-service.c.s

src/programs/controller-api.lua.o: src/programs/controller-api.lua.c.o

.PHONY : src/programs/controller-api.lua.o

# target to build an object file
src/programs/controller-api.lua.c.o:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/controller-api.lua.c.o
.PHONY : src/programs/controller-api.lua.c.o

src/programs/controller-api.lua.i: src/programs/controller-api.lua.c.i

.PHONY : src/programs/controller-api.lua.i

# target to preprocess a source file
src/programs/controller-api.lua.c.i:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/controller-api.lua.c.i
.PHONY : src/programs/controller-api.lua.c.i

src/programs/controller-api.lua.s: src/programs/controller-api.lua.c.s

.PHONY : src/programs/controller-api.lua.s

# target to generate assembly for a file
src/programs/controller-api.lua.c.s:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/controller-api.lua.c.s
.PHONY : src/programs/controller-api.lua.c.s

src/programs/controller-schema.sql.o: src/programs/controller-schema.sql.c.o

.PHONY : src/programs/controller-schema.sql.o

# target to build an object file
src/programs/controller-schema.sql.c.o:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/controller-schema.sql.c.o
.PHONY : src/programs/controller-schema.sql.c.o

src/programs/controller-schema.sql.i: src/programs/controller-schema.sql.c.i

.PHONY : src/programs/controller-schema.sql.i

# target to preprocess a source file
src/programs/controller-schema.sql.c.i:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/controller-schema.sql.c.i
.PHONY : src/programs/controller-schema.sql.c.i

src/programs/controller-schema.sql.s: src/programs/controller-schema.sql.c.s

.PHONY : src/programs/controller-schema.sql.s

# target to generate assembly for a file
src/programs/controller-schema.sql.c.s:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/controller-schema.sql.c.s
.PHONY : src/programs/controller-schema.sql.c.s

src/programs/json.lua.o: src/programs/json.lua.c.o

.PHONY : src/programs/json.lua.o

# target to build an object file
src/programs/json.lua.c.o:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/json.lua.c.o
.PHONY : src/programs/json.lua.c.o

src/programs/json.lua.i: src/programs/json.lua.c.i

.PHONY : src/programs/json.lua.i

# target to preprocess a source file
src/programs/json.lua.c.i:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/json.lua.c.i
.PHONY : src/programs/json.lua.c.i

src/programs/json.lua.s: src/programs/json.lua.c.s

.PHONY : src/programs/json.lua.s

# target to generate assembly for a file
src/programs/json.lua.c.s:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/json.lua.c.s
.PHONY : src/programs/json.lua.c.s

src/programs/libclusterctl.o: src/programs/libclusterctl.c.o

.PHONY : src/programs/libclusterctl.o

# target to build an object file
src/programs/libclusterctl.c.o:
	$(MAKE) -f CMakeFiles/clusterd-service.dir/build.make CMakeFiles/clusterd-service.dir/src/programs/libclusterctl.c.o
	$(MAKE) -f CMakeFiles/clusterd-host.dir/build.make CMakeFiles/clusterd-host.dir/src/programs/libclusterctl.c.o
	$(MAKE) -f CMakeFiles/clusterctl.dir/build.make CMakeFiles/clusterctl.dir/src/programs/libclusterctl.c.o
	$(MAKE) -f CMakeFiles/clusterd-ns.dir/build.make CMakeFiles/clusterd-ns.dir/src/programs/libclusterctl.c.o
.PHONY : src/programs/libclusterctl.c.o

src/programs/libclusterctl.i: src/programs/libclusterctl.c.i

.PHONY : src/programs/libclusterctl.i

# target to preprocess a source file
src/programs/libclusterctl.c.i:
	$(MAKE) -f CMakeFiles/clusterd-service.dir/build.make CMakeFiles/clusterd-service.dir/src/programs/libclusterctl.c.i
	$(MAKE) -f CMakeFiles/clusterd-host.dir/build.make CMakeFiles/clusterd-host.dir/src/programs/libclusterctl.c.i
	$(MAKE) -f CMakeFiles/clusterctl.dir/build.make CMakeFiles/clusterctl.dir/src/programs/libclusterctl.c.i
	$(MAKE) -f CMakeFiles/clusterd-ns.dir/build.make CMakeFiles/clusterd-ns.dir/src/programs/libclusterctl.c.i
.PHONY : src/programs/libclusterctl.c.i

src/programs/libclusterctl.s: src/programs/libclusterctl.c.s

.PHONY : src/programs/libclusterctl.s

# target to generate assembly for a file
src/programs/libclusterctl.c.s:
	$(MAKE) -f CMakeFiles/clusterd-service.dir/build.make CMakeFiles/clusterd-service.dir/src/programs/libclusterctl.c.s
	$(MAKE) -f CMakeFiles/clusterd-host.dir/build.make CMakeFiles/clusterd-host.dir/src/programs/libclusterctl.c.s
	$(MAKE) -f CMakeFiles/clusterctl.dir/build.make CMakeFiles/clusterctl.dir/src/programs/libclusterctl.c.s
	$(MAKE) -f CMakeFiles/clusterd-ns.dir/build.make CMakeFiles/clusterd-ns.dir/src/programs/libclusterctl.c.s
.PHONY : src/programs/libclusterctl.c.s

src/programs/sha256.o: src/programs/sha256.c.o

.PHONY : src/programs/sha256.o

# target to build an object file
src/programs/sha256.c.o:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/sha256.c.o
	$(MAKE) -f CMakeFiles/clusterd-service.dir/build.make CMakeFiles/clusterd-service.dir/src/programs/sha256.c.o
	$(MAKE) -f CMakeFiles/clusterd-host.dir/build.make CMakeFiles/clusterd-host.dir/src/programs/sha256.c.o
	$(MAKE) -f CMakeFiles/clusterctl.dir/build.make CMakeFiles/clusterctl.dir/src/programs/sha256.c.o
	$(MAKE) -f CMakeFiles/clusterd-ns.dir/build.make CMakeFiles/clusterd-ns.dir/src/programs/sha256.c.o
.PHONY : src/programs/sha256.c.o

src/programs/sha256.i: src/programs/sha256.c.i

.PHONY : src/programs/sha256.i

# target to preprocess a source file
src/programs/sha256.c.i:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/sha256.c.i
	$(MAKE) -f CMakeFiles/clusterd-service.dir/build.make CMakeFiles/clusterd-service.dir/src/programs/sha256.c.i
	$(MAKE) -f CMakeFiles/clusterd-host.dir/build.make CMakeFiles/clusterd-host.dir/src/programs/sha256.c.i
	$(MAKE) -f CMakeFiles/clusterctl.dir/build.make CMakeFiles/clusterctl.dir/src/programs/sha256.c.i
	$(MAKE) -f CMakeFiles/clusterd-ns.dir/build.make CMakeFiles/clusterd-ns.dir/src/programs/sha256.c.i
.PHONY : src/programs/sha256.c.i

src/programs/sha256.s: src/programs/sha256.c.s

.PHONY : src/programs/sha256.s

# target to generate assembly for a file
src/programs/sha256.c.s:
	$(MAKE) -f CMakeFiles/clusterd-controller.dir/build.make CMakeFiles/clusterd-controller.dir/src/programs/sha256.c.s
	$(MAKE) -f CMakeFiles/clusterd-service.dir/build.make CMakeFiles/clusterd-service.dir/src/programs/sha256.c.s
	$(MAKE) -f CMakeFiles/clusterd-host.dir/build.make CMakeFiles/clusterd-host.dir/src/programs/sha256.c.s
	$(MAKE) -f CMakeFiles/clusterctl.dir/build.make CMakeFiles/clusterctl.dir/src/programs/sha256.c.s
	$(MAKE) -f CMakeFiles/clusterd-ns.dir/build.make CMakeFiles/clusterd-ns.dir/src/programs/sha256.c.s
.PHONY : src/programs/sha256.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... clusterd-controller"
	@echo "... clusterd-service"
	@echo "... clusterd-monitor"
	@echo "... clusterd-host"
	@echo "... clusterctl"
	@echo "... edit_cache"
	@echo "... clusterd-ns"
	@echo "... src/programs/clusterctl.o"
	@echo "... src/programs/clusterctl.i"
	@echo "... src/programs/clusterctl.s"
	@echo "... src/programs/clusterd-controller.o"
	@echo "... src/programs/clusterd-controller.i"
	@echo "... src/programs/clusterd-controller.s"
	@echo "... src/programs/clusterd-db.o"
	@echo "... src/programs/clusterd-db.i"
	@echo "... src/programs/clusterd-db.s"
	@echo "... src/programs/clusterd-host.o"
	@echo "... src/programs/clusterd-host.i"
	@echo "... src/programs/clusterd-host.s"
	@echo "... src/programs/clusterd-monitor.o"
	@echo "... src/programs/clusterd-monitor.i"
	@echo "... src/programs/clusterd-monitor.s"
	@echo "... src/programs/clusterd-ns.o"
	@echo "... src/programs/clusterd-ns.i"
	@echo "... src/programs/clusterd-ns.s"
	@echo "... src/programs/clusterd-service.o"
	@echo "... src/programs/clusterd-service.i"
	@echo "... src/programs/clusterd-service.s"
	@echo "... src/programs/controller-api.lua.o"
	@echo "... src/programs/controller-api.lua.i"
	@echo "... src/programs/controller-api.lua.s"
	@echo "... src/programs/controller-schema.sql.o"
	@echo "... src/programs/controller-schema.sql.i"
	@echo "... src/programs/controller-schema.sql.s"
	@echo "... src/programs/json.lua.o"
	@echo "... src/programs/json.lua.i"
	@echo "... src/programs/json.lua.s"
	@echo "... src/programs/libclusterctl.o"
	@echo "... src/programs/libclusterctl.i"
	@echo "... src/programs/libclusterctl.s"
	@echo "... src/programs/sha256.o"
	@echo "... src/programs/sha256.i"
	@echo "... src/programs/sha256.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

